In [1]:
import sys, os
if os.path.abspath('..\\Development') not in sys.path:
    sys.path.insert(0, os.path.abspath('..\\Development'))

In [2]:
from LSA import LSA
from Testing import Testing
from PreprocessingData import PreprocessingData
from Prediction import Prediction
import numpy as np
from sklearn.metrics import multilabel_confusion_matrix, classification_report

In [3]:
path = '..\..\Problem\shuffled-full-set-hashed.csv'

In [4]:
data = PreprocessingData(path)
data.DataSplit()
data.WordMapper()
data.SwapWordByMapper()
data.CategorizeForEach()
data.CatergorizeForAll()

In [5]:
lsa = LSA(data)
lsa.TF_IDF()
lsa.TopWords()

In [6]:
Input = data.TestingData['input']
Output = data.TestingData['output']

In [7]:
prediction = Prediction(lsa, data)
predictedValues = np.array(prediction.predictMany(data.TestingData['input']))

In [18]:
confusionMatrix = multilabel_confusion_matrix(Output, predictedValues, labels=list(data.keys))
confusionMatrix

[[[14637  1312]
  [  905  1794]]

 [[12133   868]
  [ 1510  4137]]

 [[15123   352]
  [ 1824  1349]]

 [[16798   533]
  [  358   959]]

 [[15130   628]
  [ 1531  1359]]

 [[18374    52]
  [   25   197]]

 [[16643   533]
  [  291  1181]]

 [[18346   234]
  [   29    39]]

 [[18341   239]
  [   22    46]]

 [[18085   288]
  [   40   235]]

 [[18244   315]
  [   50    39]]

 [[17390   950]
  [  162   146]]

 [[17970   445]
  [   97   136]]

 [[18297   164]
  [   69   118]]]


In [17]:
# confusionReport = classification_report(Output, predictedValues, labels=list(data.keys))
# print(confusionReport)

In [10]:
#SCORE
TP = confusionMatrix[0][0][0]
FN = confusionMatrix[0][0][1]
FP = confusionMatrix[0][1][0]
TN = confusionMatrix[0][1][1]

Accuracy = (TP + TN) / (TP + TN + FP + FN)
Precision = TP / (TP + FP)
Recall =  TP / (TP + FN)
F1_Score = 2 * Recall * Precision / (Recall + Precision)

print(Accuracy, Precision, Recall, F1_Score)

0.8811132561132561 0.9417706858834127 0.9177377892030848 0.9295989330284842


In [15]:
# for i in range(14):
#     TP = confusionMatrix[i][0][0]
#     FN = confusionMatrix[i][0][1]
#     FP = confusionMatrix[i][1][0]
#     TN = confusionMatrix[i][1][1]
#     print(TP+FN+FP+TN)


In [16]:
support = {}
for i in Output:
    if i in support:
        support[i] +=1
    else:
        support[i] = 1
support

{'BILL': 5647,
 'BINDER': 2699,
 'POLICY CHANGE': 3173,
 'REINSTATEMENT NOTICE': 1317,
 'APPLICATION': 68,
 'RETURNED CHECK': 222,
 'CANCELLATION NOTICE': 2890,
 'DELETION OF INTEREST': 1472,
 'CHANGE ENDORSEMENT': 275,
 'NON-RENEWAL NOTICE': 187,
 'DECLARATION': 308,
 'BILL BINDER': 89,
 'INTENT TO CANCEL NOTICE': 68,
 'EXPIRATION NOTICE': 233}